### ISSUE TITLE
Stack exhuasted

### ISSUE THREAD

**Issue by Triangleowl** [abhijitnathwani/image-processing#3]
hi, I only modified the input image file and cause stack exhausted. I think variable **_buffer_** should not be defined as a local variable, but should be dynamically applied for heap space. :)
[crash.zip](https://github.com/abhijitnathwani/image-processing/files/3994094/crash.zip)

**Comment by abhijitnathwani** [comment]
Hi @Triangleowl ,
I tried opening the `crash.bmp` file which you've uploaded. I cannot open the file. My system stopped responding. Can you check if it is correct file? Then, i can check. 
And yes, we could assign the memory dynamically. I'll add that when time permits. Feel free to raise a PR if you wish.

**Comment by Triangleowl** [comment]
hi abhijitnathwani,
Sorry, I can open the `crash.bmp` in my Windows 10 use WPS viewer, but can't open other 
Picture viewer. Because I adjusted the 18th to 25th bytes of the `crash.bmp` file, which will be assigned to `width` and `height`. This can lead to stack exhaustion or integer overflow.
I think you should do some checks to prevent integer overflow or stack exhausted.
Thank you :)
